services:
  api:
    build: .
    image: app-fastapi:latest
    restart: unless-stopped
    environment:
      APP_NAME: ${APP_NAME:-API Fabrica}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      SECRET_KEY: ${SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      DATABASE_URL: ${DATABASE_URL}
      CORS_ORIGINS: ${CORS_ORIGINS}
      SEED_ADMIN_USERNAME: ${SEED_ADMIN_USERNAME}
      SEED_ADMIN_EMAIL: ${SEED_ADMIN_EMAIL}
      SEED_ADMIN_NOMBRE: ${SEED_ADMIN_NOMBRE}
      SEED_ADMIN_PASSWORD: ${SEED_ADMIN_PASSWORD}
      SEED_ALMACEN_USERNAME: ${SEED_ALMACEN_USERNAME}
      SEED_ALMACEN_EMAIL: ${SEED_ALMACEN_EMAIL}
      SEED_ALMACEN_NOMBRE: ${SEED_ALMACEN_NOMBRE}
      SEED_ALMACEN_PASSWORD: ${SEED_ALMACEN_PASSWORD}
      SEED_VENTAS_USERNAME: ${SEED_VENTAS_USERNAME}
      SEED_VENTAS_EMAIL: ${SEED_VENTAS_EMAIL}
      SEED_VENTAS_NOMBRE: ${SEED_VENTAS_NOMBRE}
      SEED_VENTAS_PASSWORD: ${SEED_VENTAS_PASSWORD}
    ports:
      - "8000:8000"
